/**
 * Create Auth Challenge - Send OTP for both existing and new users
 */
const https = require("https");

exports.handler = async (event) => {
  console.log("=== CREATE AUTH CHALLENGE ===");
  console.log("Event:", JSON.stringify(event, null, 2));
  console.log("User exists:", !event.request.userNotFound);

  // Extract phone number from user attributes
  let mobile = event.request.userAttributes?.phone_number || event.userName;
  
  // Convert to MSG91 format (91 prefix, no +)
  if (!mobile.startsWith('91')) {
    mobile = mobile.startsWith('+91') ? mobile.substring(1) : `91${mobile}`;
  }
  
  console.log("Formatted mobile for MSG91:", mobile);
  
  // IMPORTANT: Send OTP for both existing and new users
  // The frontend will handle signup vs login logic
  const userExists = !event.request.userNotFound;
  
  event.response.privateChallengeParameters = { 
    otp: "MSG91_GENERATED",
    userExists: userExists
  };
  event.response.challengeMetadata = `OTP_CHALLENGE:MSG91_GENERATED`;
  event.response.publicChallengeParameters = {
    message: "OTP sent to your mobile number",
    userExists: userExists ? "true" : "false",
    note: "OTP generated by MSG91"
  };
  
  // Send SMS via MSG91
  try {
    const result = await sendOtpViaMsg91(mobile);
    console.log("MSG91 API result:", result);
  } catch (error) {
    console.error("Failed to send OTP:", error);
  }

  console.log("Response:", JSON.stringify(event.response, null, 2));
  console.log("=== END CREATE AUTH CHALLENGE ===");
  return event;
};

/**
 * Send OTP via MSG91 API
 */
async function sendOtpViaMsg91(mobile) {
  const MSG91_AUTH_KEY = process.env.MSG91_AUTH_KEY;
  const MSG91_TEMPLATE_ID = process.env.MSG91_TEMPLATE_ID;

  const msg91Url = `https://api.msg91.com/api/v5/otp?template_id=${MSG91_TEMPLATE_ID}&mobile=${mobile}&authkey=${MSG91_AUTH_KEY}`;

  console.log("MSG91 URL:", msg91Url);

  return new Promise((resolve, reject) => {
    const url = new URL(msg91Url);
    const options = {
      hostname: url.hostname,
      path: url.pathname + url.search,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      }
    };

    const req = https.request(options, (res) => {
      let body = '';
      res.on('data', (chunk) => body += chunk);
      res.on('end', () => {
        console.log("MSG91 Status:", res.statusCode);
        console.log("MSG91 Response:", body);
        resolve(body);
      });
    });

    req.on('error', (error) => {
      console.error("MSG91 Fetch Error:", error);
      reject(error);
    });

    req.end();
  });
}
